# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Format

on:
  push:
  pull_request:

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install clang-format
        run: sudo apt install clang-format
      - name: Format .proto files
        run: clang-format -i internal/protobuf/*.proto
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if [ -n "$(git status --porcelain)" ]; then echo "true"; else echo "false"; fi)
      - name: Commit clang-format changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'James Adair'
          git config --global user.email 'jmsadair@gmail.com'
          git commit -am "Committing clang-format changes"
          git push
